Hallo,
<br><br>
Du hast eine Einladung von deinem Freund <a style="color:<?php echo $wo['config']['btn_background_color'];?>" href="<?php echo $wo['user']['url']?>"><?php echo $wo['user']['name'];?></a> erhalten, unserer Community <a style="color:<?php echo $wo['config']['btn_background_color'];?>" href="<?php echo $wo['config']['site_url']?>"><?php echo $wo['config']['siteName']?></a> beizutreten.<br><br>
<a style="color:<?php echo $wo['config']['btn_background_color'];?>" href="<?php echo $wo['config']['site_url']?>">Registriere dich jetzt und vernetze dich mit deinen Freunden!</a>
<br><br>
<?php echo $wo['config']['siteName']?> Team,
<br>
Viele Grüße aus Hannover ❤️